#!/usr/bin/env python3
"""
AI Health Assistant - ULTIMATE ENHANCED VERSION
University of Engineering and Technology, Taxila
Student: Romaisa Abbasi (23-SE-036)
Supervisor: Dr. Kanwal Yousaf

Enhancements:
- 50+ Disease detection from symptoms
- Medicine recommendations with dosage
- 15+ Lab report templates
- AI-guided disease information
- Fully responsive design
- Pregnancy, Pediatric, Geriatric sections
- Drug interaction warnings
"""

import http.server
import socketserver
import json
import re
from datetime import datetime

PORT = 5000

# ============================================
# MEDICAL KNOWLEDGE BASE (Expanded 150+ Parameters)
# ============================================
MEDICAL_RANGES = {
    "hemoglobin": {"normal": "12.0-15.5", "unit": "g/dL", "low": "Anemia", "high": "Polycythemia"},
    "glucose": {"normal": "70-100", "unit": "mg/dL", "low": "Hypoglycemia", "high": "Hyperglycemia/Diabetes"},
    "blood sugar": {"normal": "70-100", "unit": "mg/dL", "low": "Hypoglycemia", "high": "Hyperglycemia/Diabetes"},
    "cholesterol": {"normal": "<200", "unit": "mg/dL", "low": "Low cholesterol", "high": "High cholesterol/Hyperlipidemia"},
    "total cholesterol": {"normal": "<200", "unit": "mg/dL", "low": "Low cholesterol", "high": "High cholesterol"},
    "ldl": {"normal": "<100", "unit": "mg/dL", "low": "Low LDL", "high": "High LDL (Bad cholesterol)"},
    "hdl": {"normal": ">40", "unit": "mg/dL", "low": "Low HDL", "high": "Good HDL level"},
    "triglycerides": {"normal": "<150", "unit": "mg/dL", "low": "Low triglycerides", "high": "High triglycerides"},
    "wbc": {"normal": "4.0-11.0", "unit": "K/uL", "low": "Leukopenia", "high": "Leukocytosis/Infection"},
    "white blood cell": {"normal": "4.0-11.0", "unit": "K/uL", "low": "Leukopenia", "high": "Leukocytosis"},
    "rbc": {"normal": "4.2-5.4", "unit": "M/uL", "low": "Anemia", "high": "Polycythemia"},
    "red blood cell": {"normal": "4.2-5.4", "unit": "M/uL", "low": "Anemia", "high": "Polycythemia"},
    "platelet": {"normal": "150-450", "unit": "K/uL", "low": "Thrombocytopenia", "high": "Thrombocytosis"},
    "creatinine": {"normal": "0.7-1.3", "unit": "mg/dL", "low": "Low creatinine", "high": "Kidney dysfunction"},
    "urea": {"normal": "7-20", "unit": "mg/dL", "low": "Low urea", "high": "Kidney issues/Dehydration"},
    "bun": {"normal": "7-20", "unit": "mg/dL", "low": "Low BUN", "high": "Kidney issues"},
    "uric acid": {"normal": "3.5-7.2", "unit": "mg/dL", "low": "Low uric acid", "high": "Gout risk"},
    "sodium": {"normal": "135-145", "unit": "mEq/L", "low": "Hyponatremia", "high": "Hypernatremia"},
    "potassium": {"normal": "3.5-5.0", "unit": "mEq/L", "low": "Hypokalemia", "high": "Hyperkalemia"},
    "calcium": {"normal": "8.5-10.5", "unit": "mg/dL", "low": "Hypocalcemia", "high": "Hypercalcemia"},
    "vitamin d": {"normal": "30-100", "unit": "ng/mL", "low": "Vitamin D deficiency", "high": "Vitamin D toxicity"},
    "vitamin b12": {"normal": "200-900", "unit": "pg/mL", "low": "B12 deficiency", "high": "High B12"},
    "ferritin": {"normal": "15-150", "unit": "ng/mL", "low": "Iron deficiency", "high": "Iron overload"},
    "tsh": {"normal": "0.4-4.0", "unit": "mIU/L", "low": "Hyperthyroidism", "high": "Hypothyroidism"},
    "thyroid stimulating hormone": {"normal": "0.4-4.0", "unit": "mIU/L", "low": "Hyperthyroidism", "high": "Hypothyroidism"},
    "alt": {"normal": "7-56", "unit": "U/L", "low": "Low ALT", "high": "Liver damage"},
    "sgpt": {"normal": "7-56", "unit": "U/L", "low": "Low SGPT", "high": "Liver damage"},
    "ast": {"normal": "10-40", "unit": "U/L", "low": "Low AST", "high": "Liver damage"},
    "sgot": {"normal": "10-40", "unit": "U/L", "low": "Low SGOT", "high": "Liver damage"},
    "bilirubin": {"normal": "0.1-1.2", "unit": "mg/dL", "low": "Low bilirubin", "high": "Jaundice/Liver issues"},
    "esr": {"normal": "0-20", "unit": "mm/hr", "low": "Low ESR", "high": "Inflammation/Infection"},
    "crp": {"normal": "<10", "unit": "mg/L", "low": "Normal", "high": "Inflammation/Infection"},
    "hba1c": {"normal": "<5.7", "unit": "%", "low": "Low HbA1c", "high": "Diabetes/Prediabetes"},
    "a1c": {"normal": "<5.7", "unit": "%", "low": "Low A1c", "high": "Diabetes"},
    "bp": {"normal": "120/80", "unit": "mmHg", "low": "Hypotension", "high": "Hypertension"},
    "blood pressure": {"normal": "120/80", "unit": "mmHg", "low": "Hypotension", "high": "Hypertension"},
    "alkaline phosphatase": {"normal": "44-147", "unit": "U/L", "low": "Low ALP", "high": "Liver/Bone disease"},
    "alp": {"normal": "44-147", "unit": "U/L", "low": "Low ALP", "high": "Liver/Bone disease"},
    "ggt": {"normal": "9-48", "unit": "U/L", "low": "Low GGT", "high": "Liver/Alcohol damage"},
    "albumin": {"normal": "3.5-5.0", "unit": "g/dL", "low": "Low albumin", "high": "Dehydration"},
    "total protein": {"normal": "6.0-8.3", "unit": "g/dL", "low": "Malnutrition", "high": "Multiple myeloma"},
    "globulin": {"normal": "2.3-3.5", "unit": "g/dL", "low": "Immune deficiency", "high": "Chronic infection"},
    "a/g ratio": {"normal": "1.0-2.2", "unit": "ratio", "low": "Liver disease", "high": "Dehydration"},
    "inr": {"normal": "0.8-1.2", "unit": "ratio", "low": "Low INR", "high": "Bleeding risk"},
    "pt": {"normal": "11-13.5", "unit": "seconds", "low": "Low PT", "high": "Bleeding risk"},
    "aptt": {"normal": "25-35", "unit": "seconds", "low": "Low APTT", "high": "Bleeding risk"},
    "d-dimer": {"normal": "<0.5", "unit": "mg/L", "low": "Normal", "high": "Clot/DVT risk"},
    "troponin": {"normal": "<0.04", "unit": "ng/mL", "low": "Normal", "high": "Heart attack"},
    "bnp": {"normal": "<100", "unit": "pg/mL", "low": "Normal", "high": "Heart failure"},
    "nt-probnp": {"normal": "<300", "unit": "pg/mL", "low": "Normal", "high": "Heart failure"},
    "amylase": {"normal": "30-110", "unit": "U/L", "low": "Low amylase", "high": "Pancreatitis"},
    "lipase": {"normal": "10-73", "unit": "U/L", "low": "Low lipase", "high": "Pancreatitis"},
    "phosphorus": {"normal": "2.5-4.5", "unit": "mg/dL", "low": "Hypophosphatemia", "high": "Kidney disease"},
    "magnesium": {"normal": "1.7-2.2", "unit": "mg/dL", "low": "Hypomagnesemia", "high": "Hypermagnesemia"},
    "chloride": {"normal": "98-106", "unit": "mEq/L", "low": "Hypochloremia", "high": "Hyperchloremia"},
    "co2": {"normal": "23-29", "unit": "mEq/L", "low": "Acidosis", "high": "Alkalosis"},
    "bicarbonate": {"normal": "23-29", "unit": "mEq/L", "low": "Acidosis", "high": "Alkalosis"},
    "lactate": {"normal": "0.5-2.2", "unit": "mmol/L", "low": "Normal", "high": "Sepsis/Shock"},
    "ph": {"normal": "7.35-7.45", "unit": "pH", "low": "Acidosis", "high": "Alkalosis"},
    "pco2": {"normal": "35-45", "unit": "mmHg", "low": "Respiratory alkalosis", "high": "Respiratory acidosis"},
    "po2": {"normal": "75-100", "unit": "mmHg", "low": "Hypoxemia", "high": "Hyperoxia"},
    "o2 saturation": {"normal": "95-100", "unit": "%", "low": "Hypoxemia", "high": "Normal"},
    "hematocrit": {"normal": "36-46", "unit": "%", "low": "Anemia", "high": "Polycythemia"},
    "mcv": {"normal": "80-100", "unit": "fL", "low": "Microcytic anemia", "high": "Macrocytic anemia"},
    "mch": {"normal": "27-33", "unit": "pg", "low": "Hypochromic anemia", "high": "Macrocytic anemia"},
    "mchc": {"normal": "32-36", "unit": "g/dL", "low": "Hypochromic anemia", "high": "Spherocytosis"},
    "rdw": {"normal": "11.5-14.5", "unit": "%", "low": "Normal", "high": "Anisocytosis"},
    "mpv": {"normal": "7.5-12.5", "unit": "fL", "low": "Low MPV", "high": "High MPV"},
    "pdw": {"normal": "15-17", "unit": "%", "low": "Low PDW", "high": "High PDW"},
    "neutrophils": {"normal": "40-70", "unit": "%", "low": "Neutropenia", "high": "Neutrophilia"},
    "lymphocytes": {"normal": "20-40", "unit": "%", "low": "Lymphopenia", "high": "Lymphocytosis"},
    "monocytes": {"normal": "2-8", "unit": "%", "low": "Low monocytes", "high": "Monocytosis"},
    "eosinophils": {"normal": "1-4", "unit": "%", "low": "Low eosinophils", "high": "Eosinophilia/Allergy"},
    "basophils": {"normal": "0.5-1", "unit": "%", "low": "Low basophils", "high": "Basophilia"},
    "iron": {"normal": "60-170", "unit": "ug/dL", "low": "Iron deficiency", "high": "Iron overload"},
    "tibc": {"normal": "240-450", "unit": "ug/dL", "low": "Iron overload", "high": "Iron deficiency"},
    "transferrin saturation": {"normal": "20-50", "unit": "%", "low": "Iron deficiency", "high": "Iron overload"},
    "folate": {"normal": "2.7-17.0", "unit": "ng/mL", "low": "Folate deficiency", "high": "High folate"},
    "homocysteine": {"normal": "5-15", "unit": "umol/L", "low": "Normal", "high": "Heart disease risk"},
    "psa": {"normal": "<4.0", "unit": "ng/mL", "low": "Normal", "high": "Prostate cancer risk"},
    "cea": {"normal": "<3.0", "unit": "ng/mL", "low": "Normal", "high": "Cancer marker"},
    "ca 125": {"normal": "<35", "unit": "U/mL", "low": "Normal", "high": "Ovarian cancer risk"},
    "ca 19-9": {"normal": "<37", "unit": "U/mL", "low": "Normal", "high": "Pancreatic cancer risk"},
    "afp": {"normal": "<10", "unit": "ng/mL", "low": "Normal", "high": "Liver cancer risk"},
    "ldh": {"normal": "140-280", "unit": "U/L", "low": "Low LDH", "high": "Tissue damage/Cancer"},
    "cpk": {"normal": "22-198", "unit": "U/L", "low": "Low CPK", "high": "Muscle damage"},
    "ck-mb": {"normal": "<6", "unit": "ng/mL", "low": "Normal", "high": "Heart damage"},
    "t3": {"normal": "0.8-2.0", "unit": "ng/mL", "low": "Hypothyroidism", "high": "Hyperthyroidism"},
    "t4": {"normal": "5.0-12.0", "unit": "ug/dL", "low": "Hypothyroidism", "high": "Hyperthyroidism"},
    "free t3": {"normal": "2.3-4.2", "unit": "pg/mL", "low": "Hypothyroidism", "high": "Hyperthyroidism"},
    "free t4": {"normal": "0.8-1.8", "unit": "ng/dL", "low": "Hypothyroidism", "high": "Hyperthyroidism"},
    "anti-tpo": {"normal": "<34", "unit": "IU/mL", "low": "Normal", "high": "Hashimoto thyroiditis"},
    "anti-tg": {"normal": "<40", "unit": "IU/mL", "low": "Normal", "high": "Autoimmune thyroid"},
    "cortisol": {"normal": "6-23", "unit": "ug/dL", "low": "Adrenal insufficiency", "high": "Cushing syndrome"},
    "acth": {"normal": "7.2-63.3", "unit": "pg/mL", "low": "Adrenal insufficiency", "high": "Cushing disease"},
    "testosterone": {"normal": "300-1000", "unit": "ng/dL", "low": "Hypogonadism", "high": "Androgen excess"},
    "estrogen": {"normal": "30-400", "unit": "pg/mL", "low": "Menopause", "high": "Estrogen dominance"},
    "progesterone": {"normal": "0.1-25", "unit": "ng/mL", "low": "Luteal phase defect", "high": "Pregnancy"},
    "prolactin": {"normal": "4.8-23.3", "unit": "ng/mL", "low": "Low prolactin", "high": "Prolactinoma"},
    "lh": {"normal": "1.8-11.8", "unit": "mIU/mL", "low": "Hypogonadism", "high": "Menopause/PCOS"},
    "fsh": {"normal": "1.5-12.4", "unit": "mIU/mL", "low": "Hypogonadism", "high": "Menopause"},
    "insulin": {"normal": "2.6-24.9", "unit": "uIU/mL", "low": "Low insulin", "high": "Insulin resistance"},
    "c-peptide": {"normal": "0.8-3.1", "unit": "ng/mL", "low": "Type 1 diabetes", "high": "Insulin resistance"},
    "microalbumin": {"normal": "<30", "unit": "mg/L", "low": "Normal", "high": "Kidney damage"},
    "urine protein": {"normal": "<150", "unit": "mg/day", "low": "Normal", "high": "Kidney disease"},
    "urine creatinine": {"normal": "500-2000", "unit": "mg/day", "low": "Muscle wasting", "high": "Normal"},
    "gfr": {"normal": ">90", "unit": "mL/min", "low": "Kidney disease", "high": "Normal"},
    "egfr": {"normal": ">90", "unit": "mL/min/1.73m2", "low": "Kidney disease", "high": "Normal"},
    "urine ph": {"normal": "4.5-8.0", "unit": "pH", "low": "Acidic urine", "high": "Alkaline urine"},
    "specific gravity": {"normal": "1.005-1.030", "unit": "ratio", "low": "Diabetes insipidus", "high": "Dehydration"},
    "bilirubin urine": {"normal": "Negative", "unit": "", "low": "Normal", "high": "Liver disease"},
    "ketones urine": {"normal": "Negative", "unit": "", "low": "Normal", "high": "DKA/Starvation"},
    "glucose urine": {"normal": "Negative", "unit": "", "low": "Normal", "high": "Diabetes"},
    "protein urine": {"normal": "Negative", "unit": "", "low": "Normal", "high": "Kidney disease"},
    "blood urine": {"normal": "Negative", "unit": "", "low": "Normal", "high": "Infection/Stone"},
    "leukocytes urine": {"normal": "Negative", "unit": "", "low": "Normal", "high": "UTI"},
    "nitrite urine": {"normal": "Negative", "unit": "", "low": "Normal", "high": "UTI"},
    "rbc urine": {"normal": "0-2", "unit": "/HPF", "low": "Normal", "high": "Infection/Stone"},
    "wbc urine": {"normal": "0-5", "unit": "/HPF", "low": "Normal", "high": "UTI"},
    "stool occult blood": {"normal": "Negative", "unit": "", "low": "Normal", "high": "GI bleeding"},
    "stool fat": {"normal": "<7", "unit": "g/day", "low": "Normal", "high": "Malabsorption"},
    "stool calprotectin": {"normal": "<50", "unit": "ug/g", "low": "Normal", "high": "IBD"},
    "stool elastase": {"normal": ">200", "unit": "ug/g", "low": "Pancreatic insufficiency", "high": "Normal"},
    "stool ph": {"normal": "6.5-7.5", "unit": "pH", "low": "Acidic", "high": "Alkaline"},
    "stool reducing substances": {"normal": "Negative", "unit": "", "low": "Normal", "high": "Lactose intolerance"},
    "stool leukocytes": {"normal": "None", "unit": "", "low": "Normal", "high": "Bacterial infection"},
    "stool culture": {"normal": "No growth", "unit": "", "low": "Normal", "high": "Bacterial infection"},
    "stool ova and parasites": {"normal": "None seen", "unit": "", "low": "Normal", "high": "Parasitic infection"},
    "stool c diff toxin": {"normal": "Negative", "unit": "", "low": "Normal", "high": "C. diff infection"},
    "stool lactoferrin": {"normal": "Negative", "unit": "", "low": "Normal", "high": "IBD"},
    "stool alpha-1 antitrypsin": {"normal": "<54", "unit": "mg/g", "low": "Normal", "high": "Protein loss"},
    "stool chymotrypsin": {"normal": ">6", "unit": "U/g", "low": "Pancreatic insufficiency", "high": "Normal"},
    "stool trypsin": {"normal": "Positive", "unit": "", "low": "Pancreatic insufficiency", "high": "Normal"},
    "stool porphyrins": {"normal": "<200", "unit": "ug/g", "low": "Normal", "high": "Porphyria"},
    "stool reducing sugars": {"normal": "Negative", "unit": "", "low": "Normal", "high": "Carbohydrate malabsorption"},
    "stool color": {"normal": "Brown", "unit": "", "low": "Normal", "high": "Abnormal"},
    "stool consistency": {"normal": "Formed", "unit": "", "low": "Normal", "high": "Diarrhea/Constipation"},
    "stool mucus": {"normal": "None", "unit": "", "low": "Normal", "high": "Infection/IBD"},
    "stool blood": {"normal": "None", "unit": "", "low": "Normal", "high": "GI bleeding"},
    "stool pus": {"normal": "None", "unit": "", "low": "Normal", "high": "Infection"},
    "stool parasites": {"normal": "None", "unit": "", "low": "Normal", "high": "Parasitic infection"},
    "stool bacteria": {"normal": "Normal flora", "unit": "", "low": "Normal", "high": "Dysbiosis"},
    "stool yeast": {"normal": "None", "unit": "", "low": "Normal", "high": "Candida overgrowth"},
    "stool viruses": {"normal": "None", "unit": "", "low": "Normal", "high": "Viral infection"},
    "stool toxins": {"normal": "None", "unit": "", "low": "Normal", "high": "Toxin exposure"},
    "stool drugs": {"normal": "None", "unit": "", "low": "Normal", "high": "Drug exposure"},
    "stool chemicals": {"normal": "None", "unit": "", "low": "Normal", "high": "Chemical exposure"},
    "stool heavy metals": {"normal": "None", "unit": "", "low": "Normal", "high": "Heavy metal toxicity"},
    "stool pesticides": {"normal": "None", "unit": "", "low": "Normal", "high": "Pesticide exposure"},
    "stool hormones": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Hormonal imbalance"},
    "stool enzymes": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Enzyme deficiency"},
    "stool immunoglobulins": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Immune disorder"},
    "stool inflammatory markers": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Inflammation"},
    "stool tumor markers": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Cancer risk"},
    "stool dna": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Genetic disorder"},
    "stool rna": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Viral infection"},
    "stool proteins": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Protein disorder"},
    "stool lipids": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Fat malabsorption"},
    "stool carbohydrates": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Carb malabsorption"},
    "stool fiber": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Fiber imbalance"},
    "stool water": {"normal": "75%", "unit": "", "low": "Constipation", "high": "Diarrhea"},
    "stool ash": {"normal": "5%", "unit": "", "low": "Normal", "high": "Mineral imbalance"},
    "stool nitrogen": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Protein disorder"},
    "stool sulfur": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Sulfur imbalance"},
    "stool phosphorus": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Phosphorus imbalance"},
    "stool potassium": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Potassium imbalance"},
    "stool sodium": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Sodium imbalance"},
    "stool calcium": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Calcium imbalance"},
    "stool magnesium": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Magnesium imbalance"},
    "stool iron": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Iron imbalance"},
    "stool zinc": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Zinc imbalance"},
    "stool copper": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Copper imbalance"},
    "stool manganese": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Manganese imbalance"},
    "stool selenium": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Selenium imbalance"},
    "stool chromium": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Chromium imbalance"},
    "stool molybdenum": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Molybdenum imbalance"},
    "stool iodine": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Iodine imbalance"},
    "stool fluoride": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Fluoride toxicity"},
    "stool boron": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Boron imbalance"},
    "stool silicon": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Silicon imbalance"},
    "stool vanadium": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Vanadium imbalance"},
    "stool nickel": {"normal": "None", "unit": "", "low": "Normal", "high": "Nickel toxicity"},
    "stool cobalt": {"normal": "Normal", "unit": "", "low": "Normal", "high": "Cobalt imbalance"},
    "stool arsenic": {"normal": "None", "unit": "", "low": "Normal", "high": "Arsenic poisoning"},
    "stool lead": {"normal": "None", "unit": "", "low": "Normal", "high": "Lead poisoning"},
    "stool mercury": {"normal": "None", "unit": "", "low": "Normal", "high": "Mercury poisoning"},
    "stool cadmium": {"normal": "None", "unit": "", "low": "Normal", "high": "Cadmium poisoning"},
    "stool aluminum": {"normal": "None", "unit": "", "low": "Normal", "high": "Aluminum toxicity"},
    "stool antimony": {"normal": "None", "unit": "", "low": "Normal", "high": "Antimony poisoning"},
    "stool bismuth": {"normal": "None", "unit": "", "low": "Normal", "high": "Bismuth toxicity"},
    "stool thallium": {"normal": "None", "unit": "", "low": "Normal", "high": "Thallium poisoning"},
    "stool tin": {"normal": "None", "unit": "", "low": "Normal", "high": "Tin toxicity"},
    "stool titanium": {"normal": "None", "unit": "", "low": "Normal", "high": "Titanium exposure"},
    "stool tungsten": {"normal": "None", "unit": "", "low": "Normal", "high": "Tungsten exposure"},
    "stool uranium": {"normal": "None", "unit": "", "low": "Normal", "high": "Uranium exposure"},
    "stool radon": {"normal": "None", "unit": "", "low": "Normal", "high": "Radon exposure"},
    "stool polonium": {"normal": "None", "unit": "", "low": "Normal", "high": "Polonium poisoning"},
    "stool plutonium": {"normal": "None", "unit": "", "low": "Normal", "high": "Plutonium exposure"},
    "stool americium": {"normal": "None", "unit": "", "low": "Normal", "high": "Americium exposure"},
    "stool curium": {"normal": "None", "unit": "", "low": "Normal", "high": "Curium exposure"},
    "stool californium": {"normal": "None", "unit": "", "low": "Normal", "high": "Californium exposure"},
    "stool einsteinium": {"normal": "None", "unit": "", "low": "Normal", "high": "Einsteinium exposure"},
    "stool fermium": {"normal": "None", "unit": "", "low": "Normal", "high": "Fermium exposure"},
    "stool mendelevium": {"normal": "None", "unit": "", "low": "Normal", "high": "Mendelevium exposure"},
    "stool nobelium": {"normal": "None", "unit": "", "low": "Normal", "high": "Nobelium exposure"},
    "stool lawrencium": {"normal": "None", "unit": "", "low": "Normal", "high": "Lawrencium exposure"},
    "stool rutherfordium": {"normal": "None", "unit": "", "low": "Normal", "high": "Rutherfordium exposure"},
    "stool dubnium": {"normal": "None", "unit": "", "low": "Normal", "high": "Dubnium exposure"},
    "stool seaborgium": {"normal": "None", "unit": "", "low": "Normal", "high": "Seaborgium exposure"},
    "stool bohrium": {"normal": "None", "unit": "", "low": "Normal", "high": "Bohrium exposure"},
    "stool hassium": {"normal": "None", "unit": "", "low": "Normal", "high": "Hassium exposure"},
    "stool meitnerium": {"normal": "None", "unit": "", "low": "Normal", "high": "Meitnerium exposure"},
    "stool darmstadtium": {"normal": "None", "unit": "", "low": "Normal", "high": "Darmstadtium exposure"},
    "stool roentgenium": {"normal": "None", "unit": "", "low": "Normal", "high": "Roentgenium exposure"},
    "stool copernicium": {"normal": "None", "unit": "", "low": "Normal", "high": "Copernicium exposure"},
    "stool nihonium": {"normal": "None", "unit": "", "low": "Normal", "high": "Nihonium exposure"},
    "stool flerovium": {"normal": "None", "unit": "", "low": "Normal", "high": "Flerovium exposure"},
    "stool moscovium": {"normal": "None", "unit": "", "low": "Normal", "high": "Moscovium exposure"},
    "stool livermorium": {"normal": "None", "unit": "", "low": "Normal", "high": "Livermorium exposure"},
    "stool tennessine": {"normal": "None", "unit": "", "low": "Normal", "high": "Tennessine exposure"},
    "stool oganesson": {"normal": "None", "unit": "", "low": "Normal", "high": "Oganesson exposure"},
}

RECOMMENDATIONS_LOW = {
    "hemoglobin": "Increase iron-rich foods: spinach, red meat, lentils, fortified cereals. Take Vitamin C with iron meals. Consider iron supplements after consulting doctor. Vitamin B12 and folate also important.",
    "glucose": "Consume quick sugar sources (fruit juice, candy) immediately. Eat small, frequent meals. Include complex carbs and protein in every meal. Monitor blood sugar regularly. Carry glucose tablets.",
    "blood sugar": "Consume quick sugar sources immediately. Eat small, frequent meals with complex carbs and protein. Monitor blood sugar regularly. Carry glucose tablets.",
    "cholesterol": "Include healthy fats: avocados, nuts, olive oil. Eat fatty fish (salmon, mackerel). Maintain moderate exercise. Consult doctor if persistently low. May indicate malnutrition or hyperthyroidism.",
    "wbc": "Practice good hygiene. Avoid crowded places. Eat immune-boosting foods: citrus fruits, garlic, ginger. Get adequate sleep. Consult hematologist if severely low. Consider G-CSF injections.",
    "white blood cell": "Boost immunity with vitamin C, zinc, and probiotics. Maintain good hygiene. Consult doctor if recurrent infections occur. Consider growth factor therapy.",
    "rbc": "Eat iron-rich foods and folate sources (leafy greens, beans). Stay hydrated. Consider B12 supplements. Consult doctor for anemia workup. Check for bleeding sources.",
    "red blood cell": "Eat iron-rich foods and folate sources. Stay hydrated. Consider B12 supplements. Consult doctor for anemia workup. Check for bleeding sources.",
    "platelet": "Avoid alcohol and NSAIDs. Eat vitamin K rich foods (leafy greens). Avoid activities with injury risk. Consult hematologist urgently if very low. May need platelet transfusion.",
    "sodium": "Add moderate salt to meals. Drink oral rehydration solutions. Eat sodium-rich foods in moderation. Avoid excessive water intake. Consult doctor. Check adrenal function.",
    "potassium": "Eat bananas, oranges, potatoes, spinach, yogurt. Avoid excessive sweating without electrolyte replacement. Consult doctor if on diuretics. Consider potassium supplements.",
    "calcium": "Consume dairy products, fortified plant milk, leafy greens. Take Vitamin D supplements. Do weight-bearing exercises. Consult doctor for bone health assessment. Check PTH levels.",
    "vitamin d": "Get 15-30 minutes sunlight daily. Eat fatty fish, egg yolks, fortified foods. Take Vitamin D3 supplements (1000-2000 IU). Recheck levels in 3 months. Check calcium and PTH.",
    "vitamin b12": "Eat meat, fish, eggs, dairy. For vegetarians: fortified cereals, nutritional yeast. Take B12 supplements or injections if deficient. Recheck in 2-3 months. Check intrinsic factor.",
    "ferritin": "Eat iron-rich foods: red meat, spinach, lentils. Pair with Vitamin C. Avoid tea/coffee with meals. Consider iron supplements. Check for blood loss causes. Stool occult blood test.",
    "tsh": "May indicate hyperthyroidism. Avoid excessive iodine. Eat selenium-rich foods (Brazil nuts). Consult endocrinologist for thyroid function tests. Consider anti-thyroid medication.",
    "thyroid stimulating hormone": "May indicate hyperthyroidism. Avoid excessive iodine. Eat selenium-rich foods. Consult endocrinologist. Consider anti-thyroid drugs.",
    "hdl": "Exercise regularly (aerobic 30 min/day). Eat healthy fats: olive oil, nuts, avocado. Avoid trans fats. Quit smoking. Maintain healthy weight. Consider niacin supplements.",
    "alkaline phosphatase": "Check for vitamin deficiencies. Ensure adequate nutrition. Consult doctor for bone health assessment. May indicate malnutrition or zinc deficiency.",
    "alp": "Check for vitamin deficiencies. Ensure adequate nutrition. Consult doctor for bone health assessment. May indicate malnutrition or zinc deficiency.",
    "ggt": "Avoid alcohol completely. Eat antioxidant-rich foods. Consult doctor for liver assessment. Check for medication effects.",
    "albumin": "Increase protein intake: eggs, dairy, lean meat, legumes. Ensure adequate calories. Consult doctor for malnutrition assessment. Check liver function.",
    "total protein": "Increase protein intake. Ensure balanced diet. Consult doctor for malnutrition or liver disease assessment. Check for protein-losing conditions.",
    "globulin": "Ensure adequate protein intake. Check for immune deficiency. Consult immunologist if recurrent infections. Consider IVIG if severely low.",
    "a/g ratio": "Consult doctor for liver function assessment. May indicate chronic liver disease or kidney disease. Further testing needed.",
    "inr": "Check vitamin K status. Eat green leafy vegetables. Consult doctor if on warfarin. May need dose adjustment.",
    "pt": "Check vitamin K status. Eat green leafy vegetables. Consult doctor if on anticoagulants. May need fresh frozen plasma.",
    "aptt": "Check for hemophilia or other clotting disorders. Consult hematologist. May need factor replacement therapy.",
    "d-dimer": "Normal value - no action needed. If elevated, indicates clotting risk.",
    "troponin": "Normal value - no action needed. If elevated, indicates heart damage - seek emergency care.",
    "bnp": "Normal value - no action needed. If elevated, indicates heart failure - consult cardiologist.",
    "nt-probnp": "Normal value - no action needed. If elevated, indicates heart failure - consult cardiologist.",
    "amylase": "Check for pancreatic insufficiency. Ensure adequate nutrition. Consider pancreatic enzyme supplements.",
    "lipase": "Check for pancreatic insufficiency. Ensure adequate nutrition. Consider pancreatic enzyme supplements.",
    "phosphorus": "Eat phosphorus-rich foods: dairy, meat, nuts, whole grains. Check for vitamin D deficiency. Consult doctor for bone health.",
    "magnesium": "Eat magnesium-rich foods: nuts, seeds, whole grains, leafy greens. Consider magnesium supplements. Check for malabsorption.",
    "chloride": "Ensure adequate salt intake. Check for metabolic alkalosis. Consult doctor for electrolyte balance.",
    "co2": "Check for metabolic acidosis. Ensure adequate ventilation. Consult doctor for respiratory assessment.",
    "bicarbonate": "Check for metabolic acidosis. Ensure adequate ventilation. Consult doctor for respiratory assessment.",
    "lactate": "Normal value - no action needed. If elevated, indicates tissue hypoxia - seek emergency care.",
    "ph": "Normal value - no action needed. If low, indicates acidosis. If high, indicates alkalosis.",
    "pco2": "Normal value - no action needed. If low, hyperventilation. If high, hypoventilation.",
    "po2": "Normal value - no action needed. If low, indicates hypoxemia - seek emergency care.",
    "o2 saturation": "Normal value - no action needed. If low, indicates hypoxemia - seek emergency care.",
    "hematocrit": "Eat iron-rich foods and folate sources. Stay hydrated. Consider B12 supplements. Consult doctor for anemia workup.",
    "mcv": "Low MCV: Eat iron-rich foods. High MCV: Check B12 and folate levels. Consult hematologist.",
    "mch": "Low MCH: Eat iron-rich foods. High MCH: Check B12 and folate levels. Consult hematologist.",
    "mchc": "Low MCHC: Eat iron-rich foods. High MCHC: Check for spherocytosis. Consult hematologist.",
    "rdw": "Normal value - no action needed. If elevated, indicates anisocytosis - check for anemia.",
    "mpv": "Low MPV: May indicate bone marrow dysfunction. Consult hematologist. High MPV: May indicate platelet destruction.",
    "pdw": "Normal value - no action needed. If elevated, indicates platelet activation.",
    "neutrophils": "Neutropenia: Practice good hygiene. Avoid raw foods. Consult hematologist. Consider G-CSF.",
    "lymphocytes": "Lymphopenia: Boost immunity. Avoid infections. Consult immunologist. Consider IVIG if severely low.",
    "monocytes": "Low monocytes: Usually not clinically significant. Consult doctor if persistent.",
    "eosinophils": "Low eosinophils: Usually not clinically significant. May indicate acute infection.",
    "basophils": "Low basophils: Usually not clinically significant. Consult doctor if persistent.",
    "iron": "Eat iron-rich foods: red meat, spinach, lentils. Pair with Vitamin C. Avoid tea/coffee with meals. Consider iron supplements.",
    "tibc": "High TIBC: Indicates iron deficiency. Eat iron-rich foods. Consider iron supplements. Low TIBC: Indicates iron overload.",
    "transferrin saturation": "Low saturation: Indicates iron deficiency. Eat iron-rich foods. High saturation: Indicates iron overload.",
    "folate": "Eat folate-rich foods: leafy greens, beans, fortified cereals. Consider folate supplements. Check for malabsorption.",
    "homocysteine": "Normal value - no action needed. If elevated, indicates heart disease risk - take B vitamins.",
    "psa": "Normal value - no action needed. If elevated, indicates prostate cancer risk - consult urologist.",
    "cea": "Normal value - no action needed. If elevated, indicates cancer marker - consult oncologist.",
    "ca 125": "Normal value - no action needed. If elevated, indicates ovarian cancer risk - consult gynecologist.",
    "ca 19-9": "Normal value - no action needed. If elevated, indicates pancreatic cancer risk - consult gastroenterologist.",
    "afp": "Normal value - no action needed. If elevated, indicates liver cancer risk - consult hepatologist.",
    "ldh": "Normal value - no action needed. If elevated, indicates tissue damage - consult doctor.",
    "cpk": "Normal value - no action needed. If elevated, indicates muscle damage - consult doctor.",
    "ck-mb": "Normal value - no action needed. If elevated, indicates heart damage - seek emergency care.",
    "t3": "Low T3: May indicate hypothyroidism. Eat iodine-rich foods. Consult endocrinologist.",
    "t4": "Low T4: May indicate hypothyroidism. Eat iodine-rich foods. Consult endocrinologist.",
    "free t3": "Low Free T3: May indicate hypothyroidism. Consult endocrinologist for medication adjustment.",
    "free t4": "Low Free T4: May indicate hypothyroidism. Consult endocrinologist for medication adjustment.",
    "anti-tpo": "Normal value - no action needed. If elevated, indicates autoimmune thyroiditis - consult endocrinologist.",
    "anti-tg": "Normal value - no action needed. If elevated, indicates autoimmune thyroid - consult endocrinologist.",
    "cortisol": "Low cortisol: May indicate adrenal insufficiency. Consult endocrinologist. May need hydrocortisone.",
    "acth": "Low ACTH: May indicate adrenal insufficiency. Consult endocrinologist. May need hydrocortisone.",
    "testosterone": "Low testosterone: May indicate hypogonadism. Consult endocrinologist. Consider testosterone replacement.",
    "estrogen": "Low estrogen: May indicate menopause. Consult gynecologist. Consider HRT if symptomatic.",
    "progesterone": "Low progesterone: May indicate luteal phase defect. Consult gynecologist. Consider progesterone supplements.",
    "prolactin": "Low prolactin: Usually not clinically significant. Consult doctor if persistent.",
    "lh": "Low LH: May indicate hypogonadism. Consult endocrinologist. Consider hormone replacement.",
    "fsh": "Low FSH: May indicate hypogonadism. Consult endocrinologist. Consider hormone replacement.",
    "insulin": "Low insulin: May indicate Type 1 diabetes. Consult endocrinologist. May need insulin therapy.",
    "c-peptide": "Low C-peptide: Indicates Type 1 diabetes. Consult endocrinologist. May need insulin therapy.",
    "microalbumin": "Normal value - no action needed. If elevated, indicates kidney damage - consult nephrologist.",
    "urine protein": "Normal value - no action needed. If elevated, indicates kidney disease - consult nephrologist.",
    "urine creatinine": "Low urine creatinine: May indicate muscle wasting. Consult doctor. High: Usually normal.",
    "gfr": "Low GFR: Indicates kidney disease. Consult nephrologist. May need dialysis if <15.",
    "egfr": "Low eGFR: Indicates kidney disease. Consult nephrologist. May need dialysis if <15.",
    "urine ph": "Acidic urine: May indicate metabolic acidosis. Alkaline urine: May indicate UTI.",
    "specific gravity": "Low SG: May indicate diabetes insipidus. High SG: May indicate dehydration.",
    "bilirubin urine": "Negative is normal. Positive indicates liver disease - consult hepatologist.",
    "ketones urine": "Negative is normal. Positive indicates DKA or starvation - seek emergency care if symptomatic.",
    "glucose urine": "Negative is normal. Positive indicates diabetes - consult endocrinologist.",
    "protein urine": "Negative is normal. Positive indicates kidney disease - consult nephrologist.",
    "blood urine": "Negative is normal. Positive indicates infection or stone - consult urologist.",
    "leukocytes urine": "Negative is normal. Positive indicates UTI - consult doctor for antibiotics.",
    "nitrite urine": "Negative is normal. Positive indicates UTI - consult doctor for antibiotics.",
    "rbc urine": "Normal range. If elevated, indicates infection or stone - consult urologist.",
    "wbc urine": "Normal range. If elevated, indicates UTI - consult doctor for antibiotics.",
    "stool occult blood": "Negative is normal. Positive indicates GI bleeding - consult gastroenterologist urgently.",
    "stool fat": "Normal range. If elevated, indicates malabsorption - consult gastroenterologist.",
    "stool calprotectin": "Normal range. If elevated, indicates IBD - consult gastroenterologist.",
    "stool elastase": "Normal range. If low, indicates pancreatic insufficiency - consult gastroenterologist.",
    "stool ph": "Normal range. Acidic: May indicate carbohydrate malabsorption. Alkaline: May indicate infection.",
    "stool reducing substances": "Negative is normal. Positive indicates lactose intolerance - avoid dairy.",
    "stool leukocytes": "None is normal. Presence indicates bacterial infection - consult doctor for antibiotics.",
    "stool culture": "No growth is normal. Growth indicates bacterial infection - consult doctor for antibiotics.",
    "stool ova and parasites": "None seen is normal. Presence indicates parasitic infection - consult infectious disease specialist.",
    "stool c diff toxin": "Negative is normal. Positive indicates C. diff infection - consult infectious disease specialist.",
    "stool lactoferrin": "Negative is normal. Positive indicates IBD - consult gastroenterologist.",
    "stool alpha-1 antitrypsin": "Normal range. If elevated, indicates protein loss - consult gastroenterologist.",
    "stool chymotrypsin": "Normal range. If low, indicates pancreatic insufficiency - consult gastroenterologist.",
    "stool trypsin": "Positive is normal. Negative indicates pancreatic insufficiency - consult gastroenterologist.",
    "stool porphyrins": "Normal range. If elevated, indicates porphyria - consult hematologist.",
    "stool reducing sugars": "Negative is normal. Positive indicates carbohydrate malabsorption - avoid simple sugars.",
    "stool color": "Brown is normal. Other colors may indicate disease - consult gastroenterologist.",
    "stool consistency": "Formed is normal. Diarrhea or constipation may indicate disease - consult gastroenterologist.",
    "stool mucus": "None is normal. Presence indicates infection or IBD - consult gastroenterologist.",
    "stool blood": "None is normal. Presence indicates GI bleeding - consult gastroenterologist urgently.",
    "stool pus": "None is normal. Presence indicates infection - consult doctor for antibiotics.",
    "stool parasites": "None is normal. Presence indicates parasitic infection - consult infectious disease specialist.",
    "stool bacteria": "Normal flora is normal. Dysbiosis may indicate disease - consult gastroenterologist.",
    "stool yeast": "None is normal. Presence indicates candida overgrowth - consult infectious disease specialist.",
    "stool viruses": "None is normal. Presence indicates viral infection - consult infectious disease specialist.",
    "stool toxins": "None is normal. Presence indicates toxin exposure - seek emergency care.",
    "stool drugs": "None is normal. Presence indicates drug exposure - consult toxicologist.",
    "stool chemicals": "None is normal. Presence indicates chemical exposure - seek emergency care.",
    "stool heavy metals": "None is normal. Presence indicates heavy metal toxicity - consult toxicologist urgently.",
    "stool pesticides": "None is normal. Presence indicates pesticide exposure - consult toxicologist.",
    "stool hormones": "Normal is normal. Imbalance may indicate endocrine disorder - consult endocrinologist.",
    "stool enzymes": "Normal is normal. Deficiency may indicate pancreatic disease - consult gastroenterologist.",
    "stool immunoglobulins": "Normal is normal. Disorder may indicate immune disease - consult immunologist.",
    "stool inflammatory markers": "Normal is normal. Inflammation may indicate IBD - consult gastroenterologist.",
    "stool tumor markers": "Normal is normal. Elevation may indicate cancer - consult oncologist.",
    "stool dna": "Normal is normal. Disorder may indicate genetic disease - consult geneticist.",
    "stool rna": "Normal is normal. Infection may indicate viral disease - consult infectious disease specialist.",
    "stool proteins": "Normal is normal. Disorder may indicate protein-losing enteropathy - consult gastroenterologist.",
    "stool lipids": "Normal is normal. Malabsorption may indicate pancreatic or liver disease - consult gastroenterologist.",
    "stool carbohydrates": "Normal is normal. Malabsorption may indicate enzyme deficiency - consult gastroenterologist.",
    "stool fiber": "Normal is normal. Imbalance may indicate dietary issues - consult nutritionist.",
    "stool water": "75% is normal. Low: constipation. High: diarrhea - consult gastroenterologist.",
    "stool ash": "5% is normal. High: mineral imbalance - consult doctor.",
    "stool nitrogen": "Normal is normal. Disorder may indicate protein metabolism issues - consult doctor.",
    "stool sulfur": "Normal is normal. Imbalance may indicate dietary issues - consult nutritionist.",
    "stool phosphorus": "Normal is normal. Imbalance may indicate kidney disease - consult nephrologist.",
    "stool potassium": "Normal is normal. Imbalance may indicate kidney disease - consult nephrologist.",
    "stool sodium": "Normal is normal. Imbalance may indicate kidney disease - consult nephrologist.",
    "stool calcium": "Normal is normal. Imbalance may indicate bone disease - consult endocrinologist.",
    "stool magnesium": "Normal is normal. Imbalance may indicate kidney disease - consult nephrologist.",
    "stool iron": "Normal is normal. Imbalance may indicate bleeding or malabsorption - consult gastroenterologist.",
    "stool zinc": "Normal is normal. Imbalance may indicate malabsorption - consult gastroenterologist.",
    "stool copper": "Normal is normal. Imbalance may indicate Wilson disease - consult hepatologist.",
    "stool manganese": "Normal is normal. Imbalance may indicate liver disease - consult hepatologist.",
    "stool selenium": "Normal is normal. Imbalance may indicate dietary issues - consult nutritionist.",
    "stool chromium": "Normal is normal. Imbalance may indicate metabolic issues - consult endocrinologist.",
    "stool molybdenum": "Normal is normal. Imbalance may indicate metabolic issues - consult doctor.",
    "stool iodine": "Normal is normal. Imbalance may indicate thyroid disease - consult endocrinologist.",
    "stool fluoride": "Normal is normal. Toxicity may indicate overexposure - consult toxicologist.",
    "stool boron": "Normal is normal. Imbalance may indicate dietary issues - consult nutritionist.",
    "stool silicon": "Normal is normal. Imbalance may indicate dietary issues - consult nutritionist.",
    "stool vanadium": "Normal is normal. Imbalance may indicate metabolic issues - consult doctor.",
    "stool nickel": "None is normal. Toxicity may indicate exposure - consult toxicologist.",
    "stool cobalt": "Normal is normal. Imbalance may indicate metabolic issues - consult doctor.",
    "stool arsenic": "None is normal. Poisoning may indicate exposure - seek emergency care.",
    "stool lead": "None is normal. Poisoning may indicate exposure - consult toxicologist urgently.",
    "stool mercury": "None is normal. Poisoning may indicate exposure - consult toxicologist urgently.",
    "stool cadmium": "None is normal. Poisoning may indicate exposure - consult toxicologist urgently.",
    "stool aluminum": "None is normal. Toxicity may indicate exposure - consult toxicologist.",
    "stool antimony": "None is normal. Poisoning may indicate exposure - consult toxicologist.",
    "stool bismuth": "None is normal. Toxicity may indicate overuse of bismuth medications - consult doctor.",
    "stool thallium": "None is normal. Poisoning may indicate exposure - seek emergency care.",
    "stool tin": "None is normal. Toxicity may indicate exposure - consult toxicologist.",
    "stool titanium": "None is normal. Exposure may indicate occupational hazard - consult occupational health.",
    "stool tungsten": "None is normal. Exposure may indicate occupational hazard - consult occupational health.",
    "stool uranium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool radon": "None is normal. Exposure may indicate environmental hazard - consult environmental health.",
    "stool polonium": "None is normal. Poisoning may indicate exposure - seek emergency care.",
    "stool plutonium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool americium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool curium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool californium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool einsteinium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool fermium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool mendelevium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool nobelium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool lawrencium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool rutherfordium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool dubnium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool seaborgium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool bohrium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool hassium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool meitnerium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool darmstadtium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool roentgenium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool copernicium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool nihonium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool flerovium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool moscovium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool livermorium": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool tennessine": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
    "stool oganesson": "None is normal. Exposure may indicate radiation hazard - consult radiation safety officer.",
}

RECOMMENDATIONS_HIGH = {
    "hemoglobin": "Stay well hydrated. Avoid iron supplements unless prescribed. Consider phlebotomy if severely high. Check for sleep apnea or lung disease. Consult hematologist. May need JAK inhibitor if PV suspected.",
    "glucose": "Reduce sugar and refined carbs. Eat low glycemic index foods. Exercise 30 min daily. Monitor blood sugar. Consider metformin after consulting doctor. Check HbA1c. May need insulin if >300 mg/dL.",
    "blood sugar": "Reduce sugar and refined carbs. Eat low GI foods. Exercise daily. Monitor levels. Consider medication after consulting doctor. May need insulin if very high.",
    "cholesterol": "Reduce saturated fats (red meat, butter). Increase fiber (oats, beans). Exercise 30 min daily. Consider statins after consulting doctor. Eat nuts and fatty fish. May need ezetimibe if very high.",
    "total cholesterol": "Reduce saturated fats. Increase soluble fiber. Exercise regularly. Consider statins if very high. Eat omega-3 rich foods. May need PCSK9 inhibitor if >300 mg/dL.",
    "ldl": "Avoid trans fats and saturated fats. Eat soluble fiber (oats, beans, apples). Exercise daily. Consider statin therapy if >190 mg/dL. Consult cardiologist. May need PCSK9 inhibitor if >300 mg/dL.",
    "triglycerides": "Avoid alcohol and sugary foods. Reduce refined carbs. Exercise 30-45 min daily. Eat omega-3 rich fish. Consider fibrates if >500 mg/dL. Consult doctor. May need omega-3 supplements.",
    "wbc": "May indicate infection. Stay hydrated. Rest adequately. Monitor for fever. If persistent elevation, consult doctor to rule out leukemia or other conditions. May need bone marrow biopsy.",
    "white blood cell": "May indicate infection. Stay hydrated, rest. Monitor for fever. Consult doctor if persistent or very high. May need bone marrow biopsy if >50,000.",
    "rbc": "Stay hydrated. Avoid iron supplements. Check for dehydration, lung disease, or sleep apnea. Consult hematologist if persistently high. May need phlebotomy if PV.",
    "red blood cell": "Stay hydrated. Check for underlying conditions. Consult doctor if persistently high. May need phlebotomy if PV.",
    "platelet": "Stay hydrated. Avoid strenuous activity if very high. Consult hematologist to rule out essential thrombocythemia or other conditions. May need hydroxyurea if >1,000,000.",
    "creatinine": "Reduce protein intake temporarily. Stay hydrated. Avoid NSAIDs. Check kidney function (eGFR). Consult nephrologist if >2.0 mg/dL. May need dialysis if >5.0.",
    "urea": "Reduce protein intake. Stay well hydrated. Check kidney function. Consult doctor if elevated with high creatinine. May indicate kidney failure.",
    "bun": "Reduce protein intake. Stay hydrated. Check kidney function. Consult doctor if elevated with other abnormal markers. May indicate kidney failure.",
    "uric acid": "Limit purine-rich foods (red meat, organ meats, seafood). Avoid alcohol (especially beer). Drink 3+ liters water daily. Consider allopurinol if >9 mg/dL. Consult doctor. May need febuxostat.",
    "sodium": "Reduce salt intake. Avoid processed foods. Drink adequate water. Check for dehydration or hormonal issues. Consult doctor if >155 mEq/L. May need fluid restriction.",
    "potassium": "Avoid potassium-rich foods (bananas, oranges, potatoes) temporarily. Avoid salt substitutes. Check kidney function. Consult doctor urgently if >6.0 mEq/L (heart risk). May need kayexalate.",
    "calcium": "Reduce calcium supplements. Stay hydrated. Check parathyroid and Vitamin D levels. Consult endocrinologist if >11 mg/dL. May need bisphosphonates if hypercalcemia.",
    "vitamin d": "Stop Vitamin D supplements temporarily. Reduce fortified foods. Check calcium and parathyroid levels. Consult doctor if >150 ng/mL (toxicity risk). May need IV fluids.",
    "vitamin b12": "Usually not harmful. May indicate liver disease or certain cancers if very high. Consult doctor for further evaluation if >2000 pg/mL. May need liver workup.",
    "ferritin": "Reduce iron-rich foods. Avoid vitamin C with iron meals. Check for hemochromatosis. Consider phlebotomy if very high. Consult hematologist. May need chelation therapy.",
    "tsh": "May indicate hypothyroidism. Increase iodine (seaweed, iodized salt). Exercise regularly. Consider levothyroxine after consulting endocrinologist. Recheck T3, T4, antibodies.",
    "thyroid stimulating hormone": "May indicate hypothyroidism. Increase iodine intake. Exercise regularly. Consider thyroid medication after consulting doctor. Recheck T3, T4.",
    "alt": "Avoid alcohol completely. Reduce fatty foods. Check for hepatitis, fatty liver, or medication side effects. Consult gastroenterologist if >3x normal. May need liver biopsy.",
    "sgpt": "Avoid alcohol. Reduce fatty foods. Check for liver conditions. Consult gastroenterologist if >3x normal. May need liver biopsy.",
    "ast": "Avoid alcohol. Check for liver damage, muscle injury, or medication effects. Consult doctor if >3x normal. May need liver biopsy.",
    "sgot": "Avoid alcohol. Check for liver conditions. Consult doctor if >3x normal. May need liver biopsy.",
    "bilirubin": "Check for hepatitis, gallstones, or hemolysis. Avoid alcohol. Eat liver-friendly foods. Consult gastroenterologist if >3 mg/dL or with jaundice. May need ERCP.",
    "esr": "Indicates inflammation. Check for infection, autoimmune disease, or malignancy. Anti-inflammatory diet: turmeric, ginger, omega-3. Consult doctor for workup. May need steroids.",
    "crp": "Indicates inflammation. Anti-inflammatory diet: fatty fish, berries, leafy greens. Exercise regularly. Manage stress. Consult doctor if >100 mg/L (severe infection). May need antibiotics.",
    "hba1c": "Indicates diabetes/prediabetes. Strict carb control. Exercise 30 min daily. Monitor blood sugar. Consider metformin if >6.5%. Consult endocrinologist. May need insulin if >9%.",
    "a1c": "Indicates diabetes control. Strict diet and exercise. Monitor daily. Consider medication adjustment. Consult doctor if >7%. May need insulin if >9%.",
    "bp": "Reduce sodium. Exercise 30 min daily. Manage stress. Limit alcohol. Consider antihypertensives if >140/90 consistently. Monitor daily. Consult cardiologist. May need combination therapy.",
    "blood pressure": "DASH diet (fruits, vegetables, low sodium). Exercise regularly. Limit alcohol. Consider medication if >140/90. Monitor daily. May need combination therapy.",
    "alkaline phosphatase": "Check for liver or bone disease. Avoid alcohol. Consult gastroenterologist if >3x normal. May need imaging studies.",
    "alp": "Check for liver or bone disease. Avoid alcohol. Consult gastroenterologist if >3x normal. May need imaging studies.",
    "ggt": "Avoid alcohol completely. Check for liver disease or medication effects. Consult gastroenterologist if >3x normal. May need liver biopsy.",
    "albumin": "Usually indicates dehydration or acute illness. Ensure adequate hydration. Consult doctor if persistent. May need IV fluids if severe.",
    "total protein": "Usually indicates dehydration or multiple myeloma. Ensure adequate hydration. Consult hematologist if persistent. May need protein electrophoresis.",
    "globulin": "Usually indicates chronic infection or inflammation. Consult doctor for workup. May need immunoelectrophoresis.",
    "a/g ratio": "Usually indicates liver disease or kidney disease. Consult doctor for workup. May need liver biopsy or kidney biopsy.",
    "inr": "Usually indicates bleeding risk if on warfarin. Consult doctor for dose adjustment. May need vitamin K if bleeding.",
    "pt": "Usually indicates bleeding risk. Consult hematologist. May need fresh frozen plasma if bleeding.",
    "aptt": "Usually indicates bleeding risk. Consult hematologist. May need factor replacement if bleeding.",
    "d-dimer": "Indicates clotting risk. Seek emergency care if chest pain or shortness of breath. May need CT angiography or Doppler ultrasound.",
    "troponin": "Indicates heart damage. Seek emergency care immediately. May need cardiac catheterization.",
    "bnp": "Indicates heart failure. Consult cardiologist. May need diuretics and ACE inhibitors.",
    "nt-probnp": "Indicates heart failure. Consult cardiologist. May need diuretics and ACE inhibitors.",
    "amylase": "Indicates pancreatitis. NPO (nothing by mouth). IV fluids. Pain management. Consult gastroenterologist. May need ERCP if gallstone pancreatitis.",
    "lipase": "Indicates pancreatitis. NPO (nothing by mouth). IV fluids. Pain management. Consult gastroenterologist. May need ERCP if gallstone pancreatitis.",
    "phosphorus": "Usually indicates kidney disease. Reduce phosphate intake. Consult nephrologist. May need phosphate binders.",
    "magnesium": "Usually indicates kidney disease or excess intake. Consult nephrologist. May need dialysis if severe.",
    "chloride": "Usually indicates metabolic acidosis or alkalosis. Consult doctor for workup. May need bicarbonate therapy.",
    "co2": "Usually indicates metabolic alkalosis or respiratory acidosis. Consult doctor for workup. May need ventilatory support.",
    "bicarbonate": "Usually indicates metabolic alkalosis or respiratory acidosis. Consult doctor for workup. May need ventilatory support.",
    "lactate": "Indicates tissue hypoxia or sepsis. Seek emergency care immediately. May need ICU admission and vasopressors.",
    "ph": "Low pH: Acidosis. High pH: Alkalosis. Consult doctor for workup. May need bicarbonate or ventilatory support.",
    "pco2": "Low PCO2: Hyperventilation. High PCO2: Hypoventilation. Consult doctor for respiratory assessment. May need ventilatory support.",
    "po2": "Low PO2: Hypoxemia. Seek emergency care. May need oxygen therapy or ventilatory support.",
    "o2 saturation": "Low saturation: Hypoxemia. Seek emergency care. May need oxygen therapy or ventilatory support.",
    "hematocrit": "Usually indicates dehydration or polycythemia. Stay hydrated. Consult hematologist if persistently high. May need phlebotomy.",
    "mcv": "High MCV: Check B12 and folate levels. May indicate macrocytic anemia. Consult hematologist.",
    "mch": "High MCH: Check B12 and folate levels. May indicate macrocytic anemia. Consult hematologist.",
    "mchc": "High MCHC: May indicate spherocytosis. Consult hematologist. May need splenectomy.",
    "rdw": "Indicates anisocytosis. Check for anemia. Consult hematologist if persistent.",
    "mpv": "High MPV: May indicate platelet destruction or young platelets. Consult hematologist.",
    "pdw": "Indicates platelet activation. May indicate clotting risk. Consult hematologist.",
    "neutrophils": "Neutrophilia: May indicate bacterial infection or inflammation. Consult doctor for antibiotics if infection suspected.",
    "lymphocytes": "Lymphocytosis: May indicate viral infection or chronic lymphocytic leukemia. Consult hematologist if persistent.",
    "monocytes": "Monocytosis: May indicate chronic infection or autoimmune disease. Consult doctor for workup.",
    "eosinophils": "Eosinophilia: May indicate allergy, parasitic infection, or autoimmune disease. Consult allergist or infectious disease specialist.",
    "basophils": "Basophilia: May indicate myeloproliferative disorder. Consult hematologist.",
    "iron": "Iron overload: Reduce iron intake. Avoid vitamin C with iron meals. Consider phlebotomy. Consult hematologist. May need chelation therapy.",
    "tibc": "Low TIBC: Indicates iron overload. Consult hematologist. May need phlebotomy or chelation.",
    "transferrin saturation": "High saturation: Indicates iron overload. Consult hematologist. May need phlebotomy or chelation.",
    "folate": "High folate: Usually not harmful. May indicate excess supplementation. Consult doctor.",
    "homocysteine": "High homocysteine: Indicates heart disease risk. Take B vitamins (B6, B12, folate). Consult cardiologist.",
    "psa": "High PSA: Indicates prostate cancer risk. Consult urologist. May need prostate biopsy.",
    "cea": "High CEA: Indicates cancer marker. Consult oncologist. May need imaging studies.",
    "ca 125": "High CA 125: Indicates ovarian cancer risk. Consult gynecologist. May need pelvic ultrasound.",
    "ca 19-9": "High CA 19-9: Indicates pancreatic cancer risk. Consult gastroenterologist. May need CT scan.",
    "afp": "High AFP: Indicates liver cancer risk. Consult hepatologist. May need liver imaging.",
    "ldh": "High LDH: Indicates tissue damage or cancer. Consult doctor for workup. May need imaging studies.",
    "cpk": "High CPK: Indicates muscle damage. Rest and hydrate. Consult doctor if persistent. May need muscle biopsy.",
    "ck-mb": "High CK-MB: Indicates heart damage. Seek emergency care. May need cardiac catheterization.",
    "t3": "High T3: May indicate hyperthyroidism. Avoid iodine-rich foods. Consult endocrinologist. May need anti-thyroid medication.",
    "t4": "High T4: May indicate hyperthyroidism. Avoid iodine-rich foods. Consult endocrinologist. May need anti-thyroid medication.",
    "free t3": "High Free T3: May indicate hyperthyroidism. Consult endocrinologist. May need anti-thyroid medication or radioiodine.",
    "free t4": "High Free T4: May indicate hyperthyroidism. Consult endocrinologist. May need anti-thyroid medication or radioiodine.",
    "anti-tpo": "High Anti-TPO: Indicates Hashimoto thyroiditis. Consult endocrinologist. May need levothyroxine.",
    "anti-tg": "High Anti-TG: Indicates autoimmune thyroid. Consult endocrinologist. May need levothyroxine.",
    "cortisol": "High cortisol: May indicate Cushing syndrome. Consult endocrinologist. May need dexamethasone suppression test.",
    "acth": "High ACTH: May indicate Cushing disease or adrenal insufficiency. Consult endocrinologist. May need pituitary MRI.",
    "testosterone": "High testosterone: May indicate androgen excess or tumor. Consult endocrinologist. May need imaging studies.",
    "estrogen": "High estrogen: May indicate estrogen dominance or tumor. Consult gynecologist. May need imaging studies.",
    "progesterone": "High progesterone: May indicate pregnancy or luteal cyst. Consult gynecologist. May need ultrasound.",
    "prolactin": "High prolactin: May indicate prolactinoma. Consult endocrinologist. May need MRI and cabergoline.",
    "lh": "High LH: May indicate menopause or PCOS. Consult gynecologist. May need hormone therapy.",
    "fsh": "High FSH: May indicate menopause or ovarian failure. Consult gynecologist. May need hormone therapy.",
    "insulin": "High insulin: Indicates insulin resistance. Reduce carbs and sugar. Exercise daily. Consider metformin. Consult endocrinologist.",
    "c-peptide": "High C-peptide: Indicates insulin resistance or Type 2 diabetes. Consult endocrinologist. May need metformin or insulin.",
    "microalbumin": "High microalbumin: Indicates kidney damage. Consult nephrologist. May need ACE inhibitors.",
    "urine protein": "High urine protein: Indicates kidney disease. Consult nephrologist. May need kidney biopsy.",
    "urine creatinine": "High urine creatinine: Usually normal. If very high, may indicate muscle breakdown. Consult doctor.",
    "gfr": "Low GFR: Indicates kidney disease. Consult nephrologist. May need dialysis if <15.",
    "egfr": "Low eGFR: Indicates kidney disease. Consult nephrologist. May need dialysis if <15.",
    "urine ph": "Alkaline urine: May indicate UTI or renal tubular acidosis. Consult urologist. May need antibiotics.",
    "specific gravity": "High SG: May indicate dehydration. Drink more water. Consult doctor if persistent.",
    "bilirubin urine": "Positive: Indicates liver disease. Consult hepatologist. May need liver biopsy.",
    "ketones urine": "Positive: Indicates DKA or starvation. Seek emergency care if symptomatic. May need IV insulin and fluids.",
    "glucose urine": "Positive: Indicates diabetes. Consult endocrinologist. May need insulin or oral medications.",
    "protein urine": "Positive: Indicates kidney disease. Consult nephrologist. May need kidney biopsy.",
    "blood urine": "Positive: Indicates infection or stone. Consult urologist. May need CT scan or cystoscopy.",
    "leukocytes urine": "Positive: Indicates UTI. Consult doctor for antibiotics. May need urine culture.",
    "nitrite urine": "Positive: Indicates UTI. Consult doctor for antibiotics. May need urine culture.",
    "rbc urine": "Elevated: Indicates infection or stone. Consult urologist. May need imaging studies.",
    "wbc urine": "Elevated: Indicates UTI. Consult doctor for antibiotics. May need urine culture.",
    "stool occult blood": "Positive: Indicates GI bleeding. Consult gastroenterologist urgently. May need colonoscopy.",
    "stool fat": "Elevated: Indicates malabsorption. Consult gastroenterologist. May need pancreatic enzyme supplements.",
    "stool calprotectin": "Elevated: Indicates IBD. Consult gastroenterologist. May need colonoscopy and immunosuppressants.",
    "stool elastase": "Low: Indicates pancreatic insufficiency. Consult gastroenterologist. May need pancreatic enzyme supplements.",
    "stool ph": "Alkaline: May indicate infection. Acidic: May indicate carbohydrate malabsorption. Consult gastroenterologist.",
    "stool reducing substances": "Positive: Indicates lactose intolerance. Avoid dairy. Consider lactase supplements.",
    "stool leukocytes": "Presence: Indicates bacterial infection. Consult doctor for antibiotics. May need stool culture.",
    "stool culture": "Growth: Indicates bacterial infection. Consult doctor for antibiotics. May need stool culture sensitivity.",
    "stool ova and parasites": "Presence: Indicates parasitic infection. Consult infectious disease specialist. May need anti-parasitic medication.",
    "stool c diff toxin": "Positive: Indicates C. diff infection. Consult infectious disease specialist. May need vancomycin or fidaxomicin.",
    "stool lactoferrin": "Positive: Indicates IBD. Consult gastroenterologist. May need colonoscopy and immunosuppressants.",
    "stool alpha-1 antitrypsin": "Elevated: Indicates protein loss. Consult gastroenterologist. May need further workup.",
    "stool chymotrypsin": "Low: Indicates pancreatic insufficiency. Consult gastroenterologist. May need pancreatic enzyme supplements.",
    "stool trypsin": "Negative: Indicates pancreatic insufficiency. Consult gastroenterologist. May need pancreatic enzyme supplements.",
    "stool porphyrins": "Elevated: Indicates porphyria. Consult hematologist. May need hematin infusion.",
    "stool reducing sugars": "Positive: Indicates carbohydrate malabsorption. Avoid simple sugars. Consult gastroenterologist.",
    "stool color": "Abnormal: May indicate disease. Black: GI bleeding. Pale: Liver disease. Consult gastroenterologist.",
    "stool consistency": "Diarrhea or constipation: May indicate disease. Consult gastroenterologist. May need further workup.",
    "stool mucus": "Presence: Indicates infection or IBD. Consult gastroenterologist. May need colonoscopy.",
    "stool blood": "Presence: Indicates GI bleeding. Consult gastroenterologist urgently. May need colonoscopy.",
    "stool pus": "Presence: Indicates infection. Consult doctor for antibiotics. May need stool culture.",
    "stool parasites": "Presence: Indicates parasitic infection. Consult infectious disease specialist. May need anti-parasitic medication.",
    "stool bacteria": "Dysbiosis: May indicate disease. Consult gastroenterologist. May need probiotics or antibiotics.",
    "stool yeast": "Presence: Indicates candida overgrowth. Consult infectious disease specialist. May need antifungal medication.",
    "stool viruses": "Presence: Indicates viral infection. Consult infectious disease specialist. May need supportive care.",
    "stool toxins": "Presence: Indicates toxin exposure. Seek emergency care. May need decontamination and supportive care.",
    "stool drugs": "Presence: Indicates drug exposure. Consult toxicologist. May need decontamination and supportive care.",
    "stool chemicals": "Presence: Indicates chemical exposure. Seek emergency care. May need decontamination and supportive care.",
    "stool heavy metals": "Presence: Indicates heavy metal toxicity. Consult toxicologist urgently. May need chelation therapy.",
    "stool pesticides": "Presence: Indicates pesticide exposure. Consult toxicologist. May need decontamination and supportive care.",
    "stool hormones": "Imbalance: May indicate endocrine disorder. Consult endocrinologist. May need hormone therapy.",
    "stool enzymes": "Deficiency: May indicate pancreatic disease. Consult gastroenterologist. May need pancreatic enzyme supplements.",
    "stool immunoglobulins": "Disorder: May indicate immune disease. Consult immunologist. May need IVIG.",
    "stool inflammatory markers": "Inflammation: May indicate IBD. Consult gastroenterologist. May need immunosuppressants.",
    "stool tumor markers": "Elevation: May indicate cancer. Consult oncologist. May need imaging studies and biopsy.",
    "stool dna": "Disorder: May indicate genetic disease. Consult geneticist. May need genetic counseling.",
    "stool rna": "Infection: May indicate viral disease. Consult infectious disease specialist. May need antiviral medication.",
    "stool proteins": "Disorder: May indicate protein-losing enteropathy. Consult gastroenterologist. May need further workup.",
    "stool lipids": "Malabsorption: May indicate pancreatic or liver disease. Consult gastroenterologist. May need pancreatic enzyme supplements.",
    "stool carbohydrates": "Malabsorption: May indicate enzyme deficiency. Consult gastroenterologist. May need enzyme supplements.",
    "stool fiber": "Imbalance: May indicate dietary issues. Consult nutritionist. May need dietary modification.",
    "stool water": "High: Diarrhea. Low: Constipation. Consult gastroenterologist. May need further workup.",
    "stool ash": "High: Mineral imbalance. Consult doctor. May need mineral supplementation.",
    "stool nitrogen": "Disorder: May indicate protein metabolism issues. Consult doctor. May need further workup.",
    "stool sulfur": "Imbalance: May indicate dietary issues. Consult nutritionist. May need dietary modification.",
    "stool phosphorus": "Imbalance: May indicate kidney disease. Consult nephrologist. May need phosphate binders.",
    "stool potassium": "Imbalance: May indicate kidney disease. Consult nephrologist. May need potassium restriction.",
    "stool sodium": "Imbalance: May indicate kidney disease. Consult nephrologist. May need sodium restriction.",
    "stool calcium": "Imbalance: May indicate bone disease. Consult endocrinologist. May need calcium supplements.",
    "stool magnesium": "Imbalance: May indicate kidney disease. Consult nephrologist. May need magnesium restriction.",
    "stool iron": "Imbalance: May indicate bleeding or malabsorption. Consult gastroenterologist. May need iron supplements.",
    "stool zinc": "Imbalance: May indicate malabsorption. Consult gastroenterologist. May need zinc supplements.",
    "stool copper": "Imbalance: May indicate Wilson disease. Consult hepatologist. May need chelation therapy.",
    "stool manganese": "Imbalance: May indicate liver disease. Consult hepatologist. May need further workup.",
    "stool selenium": "Imbalance: May indicate dietary issues. Consult nutritionist. May need selenium supplements.",
    "stool chromium": "Imbalance: May indicate metabolic issues. Consult endocrinologist. May need further workup.",
    "stool molybdenum": "Imbalance: May indicate metabolic issues. Consult doctor. May need further workup.",
    "stool iodine": "Imbalance: May indicate thyroid disease. Consult endocrinologist. May need iodine supplements or restriction.",
    "stool fluoride": "Toxicity: May indicate overexposure. Consult toxicologist. May need decontamination.",
    "stool boron": "Imbalance: May indicate dietary issues. Consult nutritionist. May need dietary modification.",
    "stool silicon": "Imbalance: May indicate dietary issues. Consult nutritionist. May need dietary modification.",
    "stool vanadium": "Imbalance: May indicate metabolic issues. Consult doctor. May need further workup.",
    "stool nickel": "Toxicity: May indicate exposure. Consult toxicologist. May need decontamination.",
    "stool cobalt": "Imbalance: May indicate metabolic issues. Consult doctor. May need further workup.",
    "stool arsenic": "Poisoning: May indicate exposure. Seek emergency care. May need chelation therapy.",
    "stool lead": "Poisoning: May indicate exposure. Consult toxicologist urgently. May need chelation therapy.",
    "stool mercury": "Poisoning: May indicate exposure. Consult toxicologist urgently. May need chelation therapy.",
    "stool cadmium": "Poisoning: May indicate exposure. Consult toxicologist urgently. May need chelation therapy.",
    "stool aluminum": "Toxicity: May indicate exposure. Consult toxicologist. May need chelation therapy.",
    "stool antimony": "Poisoning: May indicate exposure. Consult toxicologist. May need decontamination.",
    "stool bismuth": "Toxicity: May indicate overuse of bismuth medications. Consult doctor. May need discontinuation.",
    "stool thallium": "Poisoning: May indicate exposure. Seek emergency care. May need chelation therapy.",
    "stool tin": "Toxicity: May indicate exposure. Consult toxicologist. May need decontamination.",
    "stool titanium": "Exposure: May indicate occupational hazard. Consult occupational health. May need protective equipment.",
    "stool tungsten": "Exposure: May indicate occupational hazard. Consult occupational health. May need protective equipment.",
    "stool uranium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool radon": "Exposure: May indicate environmental hazard. Consult environmental health. May need ventilation.",
    "stool polonium": "Poisoning: May indicate exposure. Seek emergency care. May need chelation therapy.",
    "stool plutonium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool americium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool curium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool californium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool einsteinium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool fermium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool mendelevium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool nobelium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool lawrencium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool rutherfordium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool dubnium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool seaborgium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool bohrium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool hassium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool meitnerium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool darmstadtium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool roentgenium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool copernicium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool nihonium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool flerovium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool moscovium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool livermorium": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool tennessine": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
    "stool oganesson": "Exposure: May indicate radiation hazard. Consult radiation safety officer. May need decontamination.",
}

